- name: Deploy todolist app
  hosts: my_infra
  become: true

  vars:
    app_dir: /opt/todolist

  tasks:
    - name: Install system dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
        update_cache: yes

    - name: Clone todolist repository
      git:
        repo: https://github.com/gaeldb/to-do-list.git
        dest: "{{ app_dir }}"
        version: main

    - name: Create virtualenv
      command: python3 -m venv venv
      args:
        chdir: "{{ app_dir }}"

    - name: Install python requirements
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

    - name: Django migrate
      command: "{{ app_dir }}/venv/bin/python manage.py migrate"
      args:
        chdir: "{{ app_dir }}"

    - name: Configure DEBUG
      lineinfile:
        path: "{{ app_dir }}/todolist/settings.py"
        regexp: '^DEBUG ='
        line: "DEBUG = {{ env == 'dev' }}"
    
    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/todolist.service
        content: |
          [Unit]
          Description=Todolist Django App
          After=network.target

          [Service]
          User=admin
          WorkingDirectory={{ app_dir }}
          ExecStart={{ app_dir }}/venv/bin/gunicorn todolist.wsgi:application --bind 0.0.0.0:8000
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start service
      systemd:
        name: todolist
        enabled: true
        state: started

    - name: Check application availability
      uri:
        url: "http://{{ ansible_host }}:8000"
        status_code: 200
